spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${MAIN_POSTGRESQL_URL}
    username: ${MAIN_POSTGRESQL_USERNAME}
    password: ${MAIN_POSTGRESQL_PASSWORD}

  flyway:
    baseline-on-migrate: true
    locations:
      - db/postgresql/migration/v1_0