spring:
  application.name: monolithic-main-runner

  config:
    import:
      - properties/db/main.database.yml
        # If we've run a service of an MSA, we would select one of these:
        # - properties/db/board.database.yml        # `board-rdb-adapter` module can provide this if team members agree.
        # - properties/db/order.database.yml        #   or we can use {spec-name}/order.{detailed-spec-name}.yml
        # - properties/db/product.database.yml      #   e.g., `repository/product.repository.yml`
        # - properties/db/{namespace}.database.yml  #   then adapters can handle the property files by themselves.
      - properties/web/main.cors.yml
